"""add subscription plan fields

Revision ID: f5a2e8806d39
Revises: b4b382153d12
Create Date: 2026-01-26 05:38:53.154735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a2e8806d39'
down_revision: Union[str, Sequence[str], None] = 'b4b382153d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_days_total', sa.Integer(), nullable=True))
    op.drop_column('users', 'subscription_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'subscription_days_total')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###
